### ISSUE TITLE
ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by oscarnevarezleal** [aws-samples/amazon-chime-sdk-classroom-demo#13]
After following the instructions detailed on the README file, using Cloud9 for build and deployment I got the following error:

```
error /home/ec2-user/environment/amazon-chime-sdk-classroom-demo/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments: 
Directory: /home/ec2-user/environment/amazon-chime-sdk-classroom-demo/node_modules/electron-chromedriver
Output:
/home/ec2-user/environment/amazon-chime-sdk-classroom-demo/node_modules/electron-chromedriver/download-chromedriver.js:21
    if (error != null) throw error
                       ^

Error: ENOSPC: no space left on device, write
``` 

My guess was that the EBS wasn't successfully resized when `cloud9-resize.sh` was called but, as far as I can tell the EC2 instance is using the right EBS with 100GB of space. I'm clueless

**Comment by aburnson** [comment]
@oscarnevarezleal I am unable to reproduce this error. When I follow the Cloud9 README instructions it works for me. Just curious, which region did you try in?

**Comment by oscarnevarezleal** [comment]
🤦‍♂️ I misspelled the region. It works.
