### ISSUE TITLE
Permissions Issue - not able to download the APp from URL

### ISSUE THREAD

**Issue by gitCodebytj** [aws-samples/amazon-chime-sdk-classroom-demo#18]
while clicking on the Host URL to download mac(ZIP) file - following error results on web request. 
An error occured - when calling CreateMultipartUpload operation:AccessDenied when aws s3 cp command is fired on Cloud9 application console.
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>X</RequestId>
<HostId>Y</HostId>
</Error>

**Comment by ltrung** [comment]
@gitCodebytj Did your user have AdministratorAccess?
From the README:
>Log into your AWS account with an IAM role that has the AdministratorAccess policy.

**Comment by simmkyu** [comment]
Please reopen the issue if you experience any further problems

**Comment by rnqayush** [comment]
I am have same issue. Is there any solution to it?
