### ISSUE TITLE
Cannot Deploy

### ISSUE THREAD

**Issue by abhijits3** [aws-samples/amazon-chime-sdk-classroom-demo#2]
When I try to deploy this app from my local machines its give me the error:
"Command aws failed with ENOENT"

I have aws cli and my keys configured on this mac and regularly deploy AWS lambda functions from it.

**Comment by simmkyu** [comment]
This classroom demo is based on the `deploy.js` script from [the Serverless Demo in the SDK repo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) that requires AWS CLI and SAM CLI.

1. Could you try again after installing SAM CLI too?

```
aws --version
sam --version
```

* [Install the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv1.html)
* [Install the AWS SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html)

2. Please make sure that your AWS IAM role has the **AdministratorAccess** policy. The script is deploying the CloudFormation stack and uploading macOS/Windows binaries to a specified S3 bucket.

We will improve README for local development.

**Comment by simmkyu** [comment]
The Chime SDK serverless demo app had the same bug that running the deploy script has failed with the ENOENT error (https://github.com/aws/amazon-chime-sdk-js/pull/307). https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/pull/9 fixed this issue. Please try again after pulling the latest commit.
