### ISSUE TITLE
Missing imports in ChimeSdkWrapper

### ISSUE THREAD

**Issue by doriansmiley** [aws-samples/amazon-chime-sdk-classroom-demo#20]
Forked repo, ran yarn, found missing imports in `ChimeSdkWrapper` for:
```
import getBaseUrl from '../utils/getBaseUrl';
import getMessagingWssUrl from '../utils/getMessagingWssUrl';
```

**Comment by ltrung** [comment]
@doriansmiley Did you deploy the app first ?
It is the first step in the README, 
```
script/deploy.js -r <region> -a <app name> -s <unique stack name> -b <unique bucket name>
```

**Comment by doriansmiley** [comment]
Nope, just messing with the react app locally right now.

**Comment by ltrung** [comment]
Unfortunately, you need to do it at least one time at the beginning in order to run it locally.

**Comment by doriansmiley** [comment]
@ltrung sounds good. Closing.
