### ISSUE TITLE
How I can run the desktop app as a website in a browser?

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-sdk-classroom-demo#24]
Hello, I want to make the web site similar UI of desktop app with using the same source code.

How I can do that?

**Comment by cmdavinder** [comment]
I would like to know this as well. Also, after creating a meeting room, how can I login to same meeting as a student? UI doesn't give me any meeting URL that I can share with other.

**Comment by vijayamin83** [comment]
You need to make the custom functionality to share the meeting url with other users.

But, I want to run the same desktop application as a website in browser.

**Comment by p-foucht** [comment]
The Classroom app is built with React. You would need to strip out React portion of the Electron app and replace any Electron-specific code that was used, [such as this](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/65abe03ea8ade6ab3db203b5c1a04313cd0be8a0/app/components/ScreenPicker.tsx#L5)

**Comment by vijayamin83** [comment]
@p-foucht it require much code changes? Can we have some short code change solution?

**Comment by simmkyu** [comment]
The classroom demo (this repo) uses Electron, a framework for creating native applications. Thus, in React components and other JavaScript files, we have used Electron APIs, such as the native window management.

We recently released Chime SDK UI Component Library for the web environment. Please try the demo that has a similar interface as in this classroom demo.
- https://github.com/aws/amazon-chime-sdk-component-library-react
- Demo: https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting

From the component-library demo, you can make the following changes to build a similar classroom.
- Add the teacher and student mode (e.g., [the teacher/student selection UI in the classroom demo](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/master/app/components/Login.tsx))
- Update the CSS styles (e.g., [the classroom demo global styles](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/master/app/app.global.css#L14-L33))

However, you might not be able to achieve the following features.
- The screen sharing view floating over other desktop windows. In a browser, we don't have controls over the window. The window management is the main reason we built the classroom demo using Electron to share screen while viewing student videos.
