### ISSUE TITLE
Improve README for local development

### ISSUE THREAD

**Issue by simmkyu** [aws-samples/amazon-chime-sdk-classroom-demo#3]
The deployment script uses Yarn, AWS CLI, and SAM CLI for building and deploying the classroom macOS and Windows binaries. These tools are pre-installed in the AWS Cloud9 environment. Developers need to install them for local development.

**Comment by oscarnevarezleal** [comment]
I've just noticed this, also `script/deploy.js` is calling `script/cloud9-resize.sh` :/ so there's no way to run the project without manually run each command defined in deploy.js

**Comment by georgemck** [comment]
Yep!

**Comment by nicklera1** [comment]
> I've just noticed this, also `script/deploy.js` is calling `script/cloud9-resize.sh` :/ so there's no way to run the project without manually run each command defined in deploy.js

Hi @oscarnevarezleal  [cloud9-resize](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/master/script/cloud9-resize.sh) script has a [logic to test if environment is Cloud9](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/master/script/cloud9-resize.sh#L7) if not script is skipped from running.

**Comment by nicklera1** [comment]
Updated readme to reflect required prerequisites.  Resolving...
