### ISSUE TITLE
Apple Mac Store Submission Error

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-sdk-classroom-demo#36]
Extending to 
https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/issues/27

Is there any way that we can test the MAS build before uploading to App Store?

**Comment by ltrung** [comment]
@vijayamin83 Unfortunately, it does not seem possible to do so at the moment https://developer.apple.com/forums/thread/651943.
