### ISSUE TITLE
Couldn't find valid filesystem superblock.

### ISSUE THREAD

**Issue by sonckluis** [aws-samples/amazon-chime-sdk-classroom-demo#47]
I have problems for deploying in cloud9, when execute:

script/deploy.js -r us-east-1  -a my-app-name -s my-unique-stack-name -b my-unique-bucket-name

occurs the next error:

CHANGED: partition=1 start=4096 old: size=20967391 end=20971487 new: size=209711071 end=209715167
Couldn't find valid filesystem superblock.

An error occurred (InvalidVolumeModification.NotFound) when calling the DescribeVolumesModifications operation: Modification for volume 'vol-xxxxxx' does not exist.

resize2fs: Bad magic number in super-block while trying to open /dev/xvda1

I have tried modifying the instance type, but the err continue. The instance is running with amazon linux

**Comment by vidya-mohan** [comment]
Resolving as a deployment issue with bucket name
