### ISSUE TITLE
audio not working properly 

### ISSUE THREAD

**Issue by kalpeshims** [aws-samples/amazon-chime-sdk-classroom-demo#49]
facing issue with audio with page load ( audio not working fine, some times getting below error and then stop audio working )

`[14799:0227/170124.920304:ERROR:webrtc_video_engine.cc(3252)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0
[14740:0227/170126.003219:ERROR:audio_rtp_receiver.cc(89)] AudioRtpReceiver::OnSetVolume: No audio channel exists.`

is there any solution without upgrading electron version ???

thanks.

**Comment by jing-chen1** [comment]
Hi @kalpeshims 

Sorry for the late response. Would like to know your electron version, so we can reproduce the error.

**Comment by kalpeshims** [comment]
Hello @jing-chen1 thanks for your reply.

I am using "electron": "9.0.5" version.

thanks.
