### ISSUE TITLE
Embed in html with electron

### ISSUE THREAD

**Issue by ximo1984** [aws-samples/amazon-chime-sdk-classroom-demo#62]
Hi,

Is it possible to run this demo inside a browser? I don't need electron part.

Thanks in advance.

**Comment by michhyun1** [comment]
Hey @ximo1984, if you're looking for a similar demo - we have a browser based demo in the [Chime SDK for Javascript](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) or the [Chime SDK React Components Library](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo).

Feel free to use the react components from this demo, but currently we haven't made the changes to run this in the browser.
