### ISSUE TITLE
on opening endpoint url its showing access denied. also there is node version compatibility error appearing. once i install node v16.3.0 it gets resolved but comes with new error

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-sdk-classroom-demo#70]
![aws error4](https://user-images.githubusercontent.com/74084740/122080550-f8e30b00-ce1b-11eb-89b3-1cb3b4078ac8.png)
![aws err1](https://user-images.githubusercontent.com/74084740/122080564-fc769200-ce1b-11eb-8fbb-7c8ab0f2fffb.png)
![aws err2](https://user-images.githubusercontent.com/74084740/122080571-fe405580-ce1b-11eb-9725-5c1ee7836f27.png)
![aws err3](https://user-images.githubusercontent.com/74084740/122080579-000a1900-ce1c-11eb-80bf-d9b285af9c2a.png)

**Comment by ltrung** [comment]
@rnqayush Could you clarify what error are you seeing in Cloud 9 with Node 16?
Also have you tried to run this in your local machine and if so do you have the same issue?

**Comment by rnqayush** [comment]
Thankyou for response, after installing node v16.3.0 I got the error which is present in last image attached to this issue. Also I have windows OS  so I face error with it hence didnt tried out in local machine. Earlier I tried chime-sdk-js there I didn't found any issue on deploying with cloud9 but this classroom deployment I am facing issues.

**Comment by rnqayush** [comment]
Kindly help me with this issue. I followed same way defined in chime-sdk-classroom doc

**Comment by xuesichao** [comment]
Hi @rnqayush sorry for late reply.
For endpoint URL showing access denied issue:
This URL is used to download the `.zip` files from S3 bucket. There is a new option called "Block Public Access settings for this account" in S3 bucket, and by default it's enabled. This is the reason why you met the issue. There're two solutions:
1. Disable this option
2. Visit the corresponding S3 bucket and download the file there.

**Comment by jing-chen1** [comment]
Closing it, feel free to reopen it if you still have problems
