### ISSUE TITLE
error of react-select and some other modules in the production build, which work well in dev environment

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-sdk-classroom-demo#72]
Hey Guys,

I am facing an issue while running the ### react-select### module (https://www.npmjs.com/package/react-select) in the production build, which works absolutely well in the development run.

Getting the following error:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/468540/123124609-7256ab00-d465-11eb-8c7e-250f6c813191.png">

Do I have to do some settings for the prod build?

**Comment by devalevenkatesh** [comment]
Hello, 

Thanks for reporting this issue. Could you please let us know what is your use-case here? I checked and did not found any `react-select` dependency in the `package.json` for this demo. Are you trying to add your custom component in this demo?

**Comment by vijayamin83** [comment]
I am customising the the code at my end, where I need to install the "react-select" plugin, but it's giving above error.

**Comment by kalpeshims** [comment]
getting same error

**Comment by michhyun1** [comment]
@vijayamin83 If you are adding more dependencies that we don't currently have in the demo, you'll have to give us more details on what you're trying to do. The purpose of this demo is to provide an example of ways to leverage the Chime SDK, but unfortunately any customizations or additions will have to be handled by the builder.

**Comment by jing-chen1** [comment]
Closing the issues for now.
