### ISSUE TITLE
App not compatibe with MacOS BigSur

### ISSUE THREAD

**Issue by theguate** [aws-samples/amazon-chime-sdk-classroom-demo#73]
After giving the appropriate permission to execute the app crashes. It seems that is not compatible with this version of MacOS

**Comment by devalevenkatesh** [comment]
Hello,

Thanks for reporting the issue. We have not yet tested the demo on BigSur. Could you please provide the error you are running into with any logs of the run or screenshot?

**Comment by ltrung** [comment]
I tried to meeting demo app on BigSur but did not see any crash. Closing for now due to inactivity. Feel free to reopen if you still have issue.
