### ISSUE TITLE
i have deployed amazon-chime-sdk-classroom-demo and getting a url but its showing access denied after clicking download for windows (zip)

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-sdk-classroom-demo#74]

**Comment by michhyun1** [comment]
Hey @rnqayush, can you try going through the blog post to see if you missed any steps: https://aws.amazon.com/blogs/business-productivity/building-a-virtual-classroom-application-using-the-amazon-chime-sdk/

More specifically this section: 

"You can now download and open the application for the OS of your choice using the URL generated in the previous step.
These applications are not signed so your local system settings may need to grant explicit permissions to open the application. To do this, Mac users can go to System Preferences > Security & Privacy > General and enable the application. Windows users can open Windows Defender and grant the permission."

**Comment by jing-chen1** [comment]
Closing it now. Please feel free to reopen it if you still have issues
