### ISSUE TITLE
Did not install on Cloud 9

### ISSUE THREAD

**Issue by SeanRenet** [aws-samples/amazon-chime-sdk-classroom-demo#76]
I followed the directions for cloud9 and got the following.

`AmplifyAdminUser:~/environment $ git clone https://github.com/aws-samples/amazon-chime-sdk-classroom-demo.git
Cloning into 'amazon-chime-sdk-classroom-demo'...
remote: Enumerating objects: 408, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 408 (delta 65), reused 83 (delta 56), pack-reused 302
Receiving objects: 100% (408/408), 2.56 MiB | 16.94 MiB/s, done.
Resolving deltas: 100% (187/187), done.
AmplifyAdminUser:~/environment $ cd amazon-chime-sdk-classroom-demo
AmplifyAdminUser:~/environment/amazon-chime-sdk-classroom-demo (master) $ script/deploy.js -r us-west-2 -a y12-chime-classroom-demo -s y12-chime-classroom-demo-stack -b y12-chime-classroom-demo-bucket
--> aws --version

--> sam --version
SAM CLI, version 1.19.0

--> npm install -g yarn

> yarn@1.22.10 preinstall /home/ec2-user/.nvm/versions/node/v10.24.1/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/home/ec2-user/.nvm/versions/node/v10.24.1/bin/yarn -> /home/ec2-user/.nvm/versions/node/v10.24.1/lib/node_modules/yarn/bin/yarn.js
/home/ec2-user/.nvm/versions/node/v10.24.1/bin/yarnpkg -> /home/ec2-user/.nvm/versions/node/v10.24.1/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.10
added 1 package in 0.909s

--> script/cloud9-resize.sh 
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
242 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package jq.x86_64 0:1.5-1.amzn2.0.2 will be installed
--> Processing Dependency: libonig.so.2()(64bit) for package: jq-1.5-1.amzn2.0.2.x86_64
--> Running transaction check
---> Package oniguruma.x86_64 0:5.9.6-1.amzn2.0.4 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package         Arch         Version                    Repository        Size
================================================================================
Installing:
 jq              x86_64       1.5-1.amzn2.0.2            amzn2-core       154 k
Installing for dependencies:
 oniguruma       x86_64       5.9.6-1.amzn2.0.4          amzn2-core       127 k

Transaction Summary
================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 281 k
Installed size: 890 k
Downloading packages:
--------------------------------------------------------------------------------
Total                                              2.2 MB/s | 281 kB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : oniguruma-5.9.6-1.amzn2.0.4.x86_64                           1/2 
  Installing : jq-1.5-1.amzn2.0.2.x86_64                                    2/2 
  Verifying  : jq-1.5-1.amzn2.0.2.x86_64                                    1/2 
  Verifying  : oniguruma-5.9.6-1.amzn2.0.4.x86_64                           2/2 

Installed:
  jq.x86_64 0:1.5-1.amzn2.0.2                                                   

Dependency Installed:
  oniguruma.x86_64 0:5.9.6-1.amzn2.0.4                                          

Complete!
{
    "VolumeModification": {
        "TargetSize": 100, 
        "OriginalMultiAttachEnabled": false, 
        "TargetVolumeType": "gp2", 
        "ModificationState": "modifying", 
        "TargetMultiAttachEnabled": false, 
        "VolumeId": "vol-00d5f3e3306a1b921", 
        "TargetIops": 300, 
        "StartTime": "2021-07-18T21:44:39.000Z", 
        "Progress": 0, 
        "OriginalVolumeType": "gp2", 
        "OriginalIops": 100, 
        "OriginalSize": 10
    }
}
CHANGED: partition=1 start=4096 old: size=20967391 end=20971487 new: size=209711071 end=209715167
Couldn't find valid filesystem superblock.

Command script/cloud9-resize.sh failed with exit code 1 signal null
+ '[' -z Y12-Chime-Classroom-Tutorial ']'
+ SIZE=100
+ sudo yum -y install jq
++ curl http://169.254.169.254/latest/meta-data//instance-id
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0   2714      0 --:--:-- --:--:-- --:--:--  2714
+ INSTANCEID=i-0382b38c572993a02
++ jq -r '.Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId'
++ aws ec2 describe-instances --instance-id i-0382b38c572993a02
+ VOLUMEID=vol-00d5f3e3306a1b921
++ jq '.VolumesModifications | length'
++ aws ec2 describe-volumes-modifications --volume-id vol-00d5f3e3306a1b921 --filters Name=modification-state,Values=optimizing,completed

An error occurred (InvalidVolumeModification.NotFound) when calling the DescribeVolumesModifications operation: Modification for volume 'vol-00d5f3e3306a1b921' does not exist.
+ '[' '' == 1 ']'
+ aws ec2 modify-volume --volume-id vol-00d5f3e3306a1b921 --size 100
++ jq '.VolumesModifications | length'
++ aws ec2 describe-volumes-modifications --volume-id vol-00d5f3e3306a1b921 --filters Name=modification-state,Values=optimizing,completed
+ '[' 0 '!=' 1 ']'
+ sleep 1
++ jq '.VolumesModifications | length'
++ aws ec2 describe-volumes-modifications --volume-id vol-00d5f3e3306a1b921 --filters Name=modification-state,Values=optimizing,completed
+ '[' 1 '!=' 1 ']'
+ sudo growpart /dev/xvda 1
+ sudo resize2fs /dev/xvda1
resize2fs 1.42.9 (28-Dec-2013)
resize2fs: Bad magic number in super-block while trying to open /dev/xvda1`

**Comment by devalevenkatesh** [comment]
Hello @SeanRenet ,

Thanks for reporting the issue. Could you please check whether the S3 bucket you are using is valid? We have a recent closed issue with a similar error #47.

**Comment by SeanRenet** [comment]
Hi @devalevenkatesh 
Yes.  Looking at the stack, it appears the only resources that were created were an ec2 server and an ec2 security group.  

Issue #47 says he misspelled the bucket name.  I am confused.  The instructions don't say you have to create the resources first.  Doesn't the script create the bucket you define in the script parameters?

`script/deploy.js -r us-west-2 -a y12-chime-classroom-demo -s y12-chime-classroom-demo-stack **-b _y12-chime-classroom-demo-bucket_**`

**Comment by jing-chen1** [comment]
Hi @SeanRenet 

Could you please try again with different bucket and stack name?

**Comment by xuesichao** [comment]
Close the issue due to no response.
Feel free to reopen it.

**Comment by SeanRenet** [comment]
HI.  What should I change the bucket and stack name to?

**Comment by SeanRenet** [comment]
@xuesichao it has not been resolved. I have no idea how to reopen the issue

**Comment by michhyun1** [comment]
@SeanRenet Yes, the bucket and stack name are defined by the parameters. You can look at the created Cloudformation stack to make sure there were no error when creating the resources

**Comment by jing-chen1** [comment]
Closing this issue, feel free to reopen it or leave a comment we can reopen it for you.

**Comment by dayowoo** [comment]
@SeanRenet @michhyun1
How can I resolve it? I have same problem with @SeanRenet ..

My command is `script/deploy.js -r us-east-1 -a ClassroomDemo -s ClassroomStack -b classroombucket`.
Does it matter? Thank you for checking my issue.
