### ISSUE TITLE
Issue in running classroom demo on my local machine

### ISSUE THREAD

**Issue by mobcoder-deepanshu** [aws-samples/amazon-chime-sdk-classroom-demo#77]
Hi Team,

I am trying to running classroom demo on my local machine as per your Readme File.

So I got this error-
Failed to create bucket: {"status":1,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[109,97,107,101,95,98,117,99,107,101,116,32,102,97,105,108,101,100,58,32,115,51,58,47,47,97,119,115,45,99,104,105,109,101,45,99,108,97,115,115,114,111,111,109,45,100,101,109,111,45,112,98,32,85,110,97,98,108,101,32,116,111,32,108,111,99,97,116,101,32,99,114,101,100,101,110,116,105,97,108,115,10]}],"pid":137308,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[109,97,107,101,95,98,117,99,107,101,116,32,102,97,105,108,101,100,58,32,115,51,58,47,47,97,119,115,45,99,104,105,109,101,45,99,108,97,115,115,114,111,111,109,45,100,101,109,111,45,112,98,32,85,110,97,98,108,101,32,116,111,32,108,111,99,97,116,101,32,99,114,101,100,101,110,116,105,97,108,115,10]}}
make_bucket failed: s3://aws-chime-classroom-demo-pb Unable to locate credentials.

Best Regards 
Deepanshu Garg
![Screenshot from 2021-07-23 09-26-00](https://user-images.githubusercontent.com/56380194/126735711-8b19091c-eb7f-49cf-af68-c44751f48efb.png)

**Comment by simmkyu** [comment]
I just cloned the repository and successfully deployed the stack under [Option 2: Deploy from your local machine](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo#option-2-deploy-from-your-local-machine). I ran the script in the following setup:

```
% node -v
v14.17.0
% npm -v
6.14.13
% sw_vers
ProductName:	macOS
ProductVersion:	11.4
```

> make_bucket failed: s3://aws-chime-classroom-demo-pb Unable to locate credentials.

1. Could you ensure that you have set up AWS credentials in your local machine? There are several options, such as storing credentials in the config file. See the Configuring the AWS CLI guide for more information about credentials.
  https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
2. Make sure that your AWS account has read and write access to S3.
3. Use the unique S3 bucket name. Once you successfully deploy the stack, you can pass the same S3 bucket name to update the existing stack.

**Comment by mobcoder-deepanshu** [comment]
Hi @simmkyu ,

I am doing same steps follow as you followed but on ubuntu.

sudo script/deploy.js -r us-east-1 -a aws-class-demo -s aws-chime-classroom-demo-pb -b aws-chime-classroom-demo-pb

I run this command.

And error will be same.

make_bucket failed: s3://aws-chime-classroom-pb-demo Unable to locate credentials.

I am ensure and checked also aws configure on my local system.
Storing credential is present there like accesskey,secretkey,region

Aws Account also have read and write access because i run another chime demo that run successfully.

And the bucket name also unique.But don't know why all time give same error as i mentioned above.

Please help me it's urgent.

Thanks

**Comment by ltrung** [comment]
Close due to inactivity.
