### ISSUE TITLE
Mac Zip File Not Being Created

### ISSUE THREAD

**Issue by rajleechaudry** [aws-samples/amazon-chime-sdk-classroom-demo#87]
Same issue as https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/issues/84
I am experiencing the same problem.  The error is saying the mac zip file didn't get created, and I don't see the mac zip file in the release directory.  So I postulate the problem is the mac zip file is not being created.  Yet, I don't see an error either.  This is on Cloud9.  You might want to reopen this, because I think something is wonky with the deploy script.

... uploading Mac installer (this may take a while) ...
--> aws s3 cp --acl public-read release/human0.zip s3://human0-releases/mac/human0.zip

Command aws failed with exit code 255 signal null

The user-provided path release/human0.zip does not exist.

_Originally posted by @rajleechaudry in https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/issues/84#issuecomment-988435452_

**Comment by houtatsu16** [comment]
Hi, I faced the same issue. Have you solved it?

**Comment by xuesichao** [comment]
Hi, did you try to deploy from local machine and check if the zip file exists? If not, could you please give it a try?

**Comment by jing-chen1** [comment]
Closing it, feel free to reopen it if you still have problem

**Comment by DjWilly** [comment]
I am facing same issue! Any progress on solution please?

**Comment by nainkunal933** [comment]
@DjWilly Replied back to you here: https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/issues/84#issuecomment-1221165248

**Comment by nainkunal933** [comment]
This issue is similar to #84. Tracking there.
