### ISSUE TITLE
Can't render video with no wisible errors

### ISSUE THREAD

**Issue by Coachtube** [aws-samples/amazon-chime-sdk-classroom-demo#88]
Hi guys!

I'm trying to implement your JS SDK API in our project based on Svelte3 and everyhting seems to be fine except the fact that I can't get the non empty video tiles. There are no errors in console, meeting session perfectly esteblished via our custom AWS Lambda endpoint and the Logger shows, that everyting is working fine. Audio and Video devices are listed and atteched without any issues and the Chrome browser indicating the video capturing from camera with the red  circle blinking on the related tab. But, there is no sign of data for rendering. Can you please tell what am I doing wrong? 

Screenshots are attached below. Thanks in advance!
Best, A!

![2](https://user-images.githubusercontent.com/30532310/145784968-e0d1a0b8-4c06-4070-84f3-5fe6ec9dafb2.png)
![1](https://user-images.githubusercontent.com/30532310/145784974-d6841586-295c-4ce4-9796-c669cfddee1e.png)

**Comment by jing-chen1** [comment]
Hi @Coachtube,

Seems like this issue is related to Chime SDK for JavaScript instead of this classroom demo. Could you please close this issue and open a new one in that [repo](https://github.com/aws/amazon-chime-sdk-js/issues/new/choose)?
