### ISSUE TITLE
Wrong Node version in Readme

### ISSUE THREAD

**Issue by vitiaaap29** [aws-samples/amazon-chime-sdk-classroom-demo#92]
`error electron-builder@22.14.5: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.7"`

I got the error when I tries to run: 
`yarn` 
with node 12.22.7

**Comment by michhyun1** [comment]
Can you try to upgrade node to 14.0.0+? That should resolve this issue. Closing this issue.
